collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.82116
color:
  saturation: 0.4191396
  brandStrength: 0.5193341
  lightness: 0.7953813
  brandColors:
    - '#FEFEFE'
    - '#1D1B1A'
    - '#C8C9CA'
    - '#E40D15'
    - '#5E5F5F'
  rhythmicContrast: 0.1756703
layout_spectrum: 0.7792696
name: aranrees
