collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7133221
color:
  saturation: 0.537594
  brandStrength: 0.5193341
  lightness: 0.8941998
  brandColors:
    - '#FFFFFF'
    - '#1A1919'
    - '#B5B4B4'
    - '#545353'
    - '#D8232A'
  rhythmicContrast: 0.5902256
layout_spectrum: 0.5657673
name: aranrees
